# Generated by Django 5.1.3 on 2025-02-06 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotoriaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
