# Generated by Django 5.1.3 on 2025-02-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotoriaAPP', '0003_remove_picture_urlimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
